---
- name: Include OS-specific variables.
  include_vars: "all.yml"

- name: "Disabling AppArmor (Ubuntu)"
  systemd:
    name: apparmor
    state: stopped
    enabled: no

- name: "Disabling UFW (Ubuntu)"
  systemd:
    name: ufw
    state: stopped
    enabled: no

- name: "Installing Some Prerequisites"
  package:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
    - git
    - htop
    - libjemalloc1
    - jq
    - mlocate
    - wget
    - awscli

- name: "Setting System Character Set"
  command: localedef -i en_US -f UTF-8 en_US.UTF-8

- name: "Adjusting System vm.swappiness"
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present

- name: "Adjusting System vm.vfs_cache_pressure"
  sysctl:
    name: vm.vfs_cache_pressure
    value: '10'
    state: present

- name: "Adjusting System txqueuelen"
  lineinfile:
    path: /etc/rc.d/rc.local
    line: '/usr/sbin/ifconfig eth0 txqueuelen 10000'
    create: yes

- name: "Adjusting System net.core.rmem_max"
  sysctl:
    name: net.core.rmem_max
    value: '16777216'
    state: present

- name: "Adjusting System net.core.wmem_max"
  sysctl:
    name: net.core.wmem_max
    value: '16777216'
    state: present

- name: "Adjusting System net.ipv4.tcp_rmem"
  sysctl:
    name: net.ipv4.tcp_rmem
    value: '4096 87380 16777216'
    state: present

- name: "Adjusting System net.ipv4.tcp_wmem"
  sysctl:
    name: net.ipv4.tcp_wmem
    value: '4096 65536 16777216'
    state: present

- name: "Adjusting System net.ipv4.tcp_no_metrics_save"
  sysctl:
    name: net.ipv4.tcp_no_metrics_save
    value: '1'
    state: present

- name: "Adjusting System net.core.netdev_max_backlog"
  sysctl:
    name: net.core.netdev_max_backlog
    value: '2500'
    state: present

- name: "Removing Conflicts"
  package:
    name: mariadb-libs
    state: absent

- name: "Getting MariaDB Enterprise Repo Setup Script"
  get_url:
    url: https://dlm.mariadb.com/enterprise-release-helpers/mariadb_es_repo_setup
    dest: /usr/local/bin/mariadb_es_repo_setup
    mode: 'a+x'

- name: "Removing Previous MariaDB Apt Repo If Necessary"
  command: rm -rf /etc/apt/sources.list.d/mariadb*

- name: "Setting Up MariaDB Enterprise Repo"
  command: /usr/local/bin/mariadb_es_repo_setup --token={{ enterprise_token }} --skip-tools --mariadb-server-version='{{ mariadb_version }}' --mariadb-maxscale-version='{{ maxscale_version }}' --apply

- name: "Creating CMAPI Folder"
  file:
    path: /opt/cmapi
    state: directory
    mode: '0755'

- name: "Downloading CMAPI Server"
  unarchive:
    src: https://dlm.mariadb.com/{{ enterprise_token }}/mariadb-enterprise-server/10.5.4-2/cmapi/mariadb-columnstore-cmapi.tar.gz
    dest: /opt/cmapi
    remote_src: yes

- name: "Checking If CMAPI Is Already Installed"
  stat:
    path: /etc/systemd/system/mariadb-columnstore-cmapi.service
  register: stat_result

- name: "Installing CMAPI Server"
  shell:
    cmd: ./service.sh install
    chdir: /opt/cmapi
  when: not stat_result.stat.exists

- name: "Installing MariaDB Items"
  package:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
    - mariadb-server
    - mariadb-plugin-columnstore
    - mariadb-backup
    - mariadb-client
    - maxscale

- name: "Disabling MariaDB Server"
  systemd:
    name: mariadb
    enabled: no

- name: "Disabling Columnstore Engine"
  systemd:
    name: mariadb-columnstore
    enabled: no

- name: "Disabling CMAPI Server"
  systemd:
    name: mariadb-columnstore-cmapi
    enabled: no

- name: "Disabling MaxScale"
  systemd:
    name: maxscale
    enabled: no

- name: "Change MariaDB binding"
  lineinfile:
    path: '/etc/mysql/mariadb.conf.d/50-server.cnf'
    regexp: '127.0.0.1'
    line: "#bind_address = 0.0.0.0"

- name: "Configuring columnstore.cnf"
  blockinfile:
   path: /etc/mysql/mariadb.conf.d/columnstore.cnf
   block: |
     character_set_server = utf8
     collation_server = utf8_general_ci
     log_bin = /var/lib/mysql/mariadb-bin
     log_bin_index = /var/lib/mysql/mariadb-bin.index
     relay_log = /var/lib/mysql/mariadb-relay
     relay_log_index = /var/lib/mysql/mariadb-relay.index
     log_slave_updates = ON
     gtid_strict_mode = ON
     log_error = /var/log/mariadb/columnstore/mariadb-error.log
     columnstore_use_import_for_batchinsert=ALWAYS

- name: download 'GOAT'
  get_url: url={{ goat_deb }} dest=/home/ubuntu/goat.deb
