---
# Version Configuration
mariadb_version: 10.5
maxscale_version: 2.5

# MariaDB Enterprise Token
enterprise_token: "{{ lookup('aws_ssm', '/production/mariadb-columnstore/enterprise-token', region='eu-west-2', decrypt=true ) }}"
